---
title: Edition Template
timezone: Etc/UTC
collections:
  docs:
    title: Documentation
    output: true
    permalink: "/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: docs
  values:
    seo:
      type: Article
    _comments:
      category: Group navigation links with this field
      order: Used to sort links in the navigation
    _options:
      content:
        width: 800
        height: 2000
- scope:
    path: ''
    type: posts
  values:
    _comments:
      type: Marks the impact of this release
url: https://long-pig.cloudvent.net
baseurl: 
google_analytics_key: 
show_full_navigation: true
logo: "/siteicon.png"
description: Product documentation template for Jekyll.
author:
  name: 
  email: 
  twitter: 
social:
  name: Edition Template
  links:
  - https://github.com/CloudCannon/edition-jekyll-template
permalink: pretty
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
types:
- minor
- major
