---
title: True Dhamma
timezone: Asia/Shanghai
collections:
  docs:
    title: Documentation
    output: true
    permalink: "/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: docs
  values:
    seo:
      type: Article
    _comments:
      category: Group navigation links with this field
      order: Used to sort links in the navigation
    _options:
      content:
        width: 800
        height: 2000
- scope:
    path: ''
    type: posts
  values:
    _comments:
      type: Marks the impact of this release
url: https://true-dhamma.github.io
baseurl: 
google_analytics_key: GTM-M9VNH47B
show_full_navigation: true
logo: "/siteicon.png"
description: "《世间成瘾与出世间觉悟》，南传上座部，佛法实修"
author:
  name: 智宁居士
  email: zhining@gmx.com
  twitter: 
social:
  name: True-Dhamma
  links:
  - https://github.com/true-dhamma
permalink: pretty
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
types:
- minor
- major
